platform :ios, '12.0'
inhibit_all_warnings!

def main
  pod 'Firebase/Firestore', '~> 6.34.0'
  pod 'SwiftLint'
end

target 'SomeChat' do
  use_frameworks!
  main
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
